service: marusia-skill-street-lights

custom:
  stage: ${opt:stage, self:provider.defaultStage}
  s3CacheBucket: ${self:service}-cache-${self:custom.stage}

provider:
  name: aws
  runtime: nodejs12.x
  profile: mrg
  defaultStage: staging
  region: eu-central-1
  environment:
    stage: ${self:custom.stage}
    region: ${self:provider.region}
    s3CacheBucket: ${self:custom.s3CacheBucket}
    mosRuAPIKey: ${ssm:mosru-opendata-api-key}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::${self:custom.s3CacheBucket}/*"

functions:
  main:
    handler: handler.main
    events:
      - http:
          path: "main"
          method: post

resources:
  Resources:
    S3CacheBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3CacheBucket}
